package messagers.util.messagetype;

public class MessageType {
	public static enum Type {
		REGISTER, LOGIN, LOGOUT, GUESTLOGIN, CHAT, NEWCHAT, TOCHAT, LEAVECHAT, GETALLCHAT, LISTACTIVEPLAYERS, KICK, GETTOPLIST, NEWULTI, TOULTI, LEAVEULTI, GETALLULTI, GAMESELECTION, PASS, PICKUPCARDS, CONFIRMGAME, PLAYCARD
	}
}
